### PR TITLE
Docker support for unimap

### PR DESCRIPTION
**Pull request by rudSarkar**
I was working around unimap and thought it will be a good idea to create PR for Docker support of unimap. So, I just jumped into it and created docker support for unimap.

You may push docker image to **Docker Hub** after this merge, so the users don't need to clone this repository to compile the docker image and use it.

The docker image will be less than 40MB.

docker image size

Instructions added in README.md with the heading **"Docker support"**. A screenshot added below for clarification.

docker support for unimap

### CODE REVIEW

**Comment by Edu4rdSHL** [comment]
Thank you so much for this PR! Really appreciate it. Between today and tomorrow, I will add the corresponding Github action which will push the Docker images to Docker Hub.

**Comment by rudSarkar** [comment]
This would be great! Thanks.

**Review by Edu4rdSHL — APPROVED** [review]

**Comment by Edu4rdSHL** [comment]
Done through https://github.com/Edu4rdSHL/unimap/blob/master/.github/workflows/cicd-to-dockerhub.yml

**Comment by rudSarkar** [comment]
> Done through https://github.com/Edu4rdSHL/unimap/blob/master/.github/workflows/cicd-to-dockerhub.yml

Can you share the docker hub username?

**Comment by rudSarkar** [comment]
I saw readme also update. Good work and thanks.

**Pull request merged**
